
package Vista;

import Controlador.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Administradorr extends javax.swing.JFrame {

    Conexion con1 = Conexion.getInstance();
    Connection conet;
    DefaultTableModel modelo;

    public Administradorr() {
        initComponents();
 // Obtener la conexión de la instancia de Conexion
        consultar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btBuscar = new javax.swing.JPanel();
        btModificacion = new javax.swing.JButton();
        ntAlta = new javax.swing.JButton();
        btBaja = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEmpleados = new javax.swing.JTable();
        AgregarCajero = new javax.swing.JButton();
        inventario1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        CredencialesCajeros = new javax.swing.JButton();

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Rectangle 22.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setUndecorated(true);
        setSize(new java.awt.Dimension(1366, 768));

        jPanel1.setBackground(new java.awt.Color(31, 31, 31));
        jPanel1.setPreferredSize(new java.awt.Dimension(1506, 745));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(482, 745));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Rectangle 22.png"))); // NOI18N
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/rectangulo.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(240, 240));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 309, 145));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Rectangle2.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 0, -1, 724));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Rectangle3.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 55)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Chedy's");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 264, 423, 68));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/clic.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 338, 50, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/logochiquito.JPG"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, -1, 59));

        jPanel3.setBackground(new java.awt.Color(31, 31, 31));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Rectangle 23.png"))); // NOI18N
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, -1, -1));

        btBuscar.setBackground(new java.awt.Color(102, 102, 102));

        btModificacion.setBackground(new java.awt.Color(204, 204, 204));
        btModificacion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btModificacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/icon.png"))); // NOI18N
        btModificacion.setText("Modificacion A Empleado");
        btModificacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        btModificacion.setBorderPainted(false);
        btModificacion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btModificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btModificacionActionPerformed(evt);
            }
        });

        ntAlta.setBackground(new java.awt.Color(204, 204, 204));
        ntAlta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ntAlta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/guardar.png"))); // NOI18N
        ntAlta.setText("Alta Empleado");
        ntAlta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        ntAlta.setBorderPainted(false);
        ntAlta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ntAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ntAltaActionPerformed(evt);
            }
        });

        btBaja.setBackground(new java.awt.Color(204, 204, 204));
        btBaja.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btBaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/eliminar.png"))); // NOI18N
        btBaja.setText("Baja de Empleado");
        btBaja.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        btBaja.setBorderPainted(false);
        btBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBajaActionPerformed(evt);
            }
        });

        btCancelar.setBackground(new java.awt.Color(83, 182, 81));
        btCancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Salir.png"))); // NOI18N
        btCancelar.setText("Salir");
        btCancelar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, new java.awt.Color(153, 255, 51), null, null));
        btCancelar.setBorderPainted(false);
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        jScrollPane1.setForeground(new java.awt.Color(255, 153, 153));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        tablaEmpleados.setBackground(new java.awt.Color(204, 204, 204));
        tablaEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "RFC", "Nombre", "Apellido_Paterno", "Apellido_Materno", "Correo", "Salario", "Puesto", "Fecha de Nacimiento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaEmpleadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaEmpleados);

        AgregarCajero.setBackground(new java.awt.Color(204, 204, 204));
        AgregarCajero.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AgregarCajero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Archivo.png"))); // NOI18N
        AgregarCajero.setText("Agregar Cajero");
        AgregarCajero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        AgregarCajero.setBorderPainted(false);
        AgregarCajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarCajeroActionPerformed(evt);
            }
        });

        inventario1.setBackground(new java.awt.Color(204, 204, 204));
        inventario1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        inventario1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/pagos.png"))); // NOI18N
        inventario1.setText("Inventario");
        inventario1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        inventario1.setBorderPainted(false);
        inventario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventario1ActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(255, 255, 204));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("EMPLEADOS");

        CredencialesCajeros.setBackground(new java.awt.Color(204, 204, 204));
        CredencialesCajeros.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CredencialesCajeros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/clientes.png"))); // NOI18N
        CredencialesCajeros.setText("Credenciales Cajeros");
        CredencialesCajeros.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        CredencialesCajeros.setBorderPainted(false);
        CredencialesCajeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CredencialesCajerosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btBuscarLayout = new javax.swing.GroupLayout(btBuscar);
        btBuscar.setLayout(btBuscarLayout);
        btBuscarLayout.setHorizontalGroup(
            btBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btBuscarLayout.createSequentialGroup()
                .addGroup(btBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(btBuscarLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 805, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btBuscarLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(btBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(btBuscarLayout.createSequentialGroup()
                                .addGap(216, 216, 216)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(117, 117, 117)
                                .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(btBuscarLayout.createSequentialGroup()
                                .addGroup(btBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(CredencialesCajeros, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ntAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(btBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(btBuscarLayout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(btModificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addComponent(btBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(btBuscarLayout.createSequentialGroup()
                                        .addGap(48, 48, 48)
                                        .addComponent(AgregarCajero, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(50, 50, 50)
                                        .addComponent(inventario1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(199, Short.MAX_VALUE))
        );
        btBuscarLayout.setVerticalGroup(
            btBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btBuscarLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(btBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(btBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btModificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ntAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(btBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btBuscarLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(btBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CredencialesCajeros, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AgregarCajero, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(btBuscarLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(inventario1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        jPanel3.add(btBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 780));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btModificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btModificacionActionPerformed
        int filaSeleccionada = tablaEmpleados.getSelectedRow();
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione un empleado para modificar.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                String rfcEmpleado = tablaEmpleados.getValueAt(filaSeleccionada, 0).toString(); // Obtener el RFC del empleado
                String nombreEmpleado = tablaEmpleados.getValueAt(filaSeleccionada, 1).toString();
                String apellidoPaternoEmpleado = tablaEmpleados.getValueAt(filaSeleccionada, 2).toString();
                String apellidoMaternoEmpleado = tablaEmpleados.getValueAt(filaSeleccionada, 3).toString();

                String sql = "SELECT Correo, Salario, Puesto FROM Empleado WHERE RFC = ?"; // Consultar usando RFC en lugar de ID
                PreparedStatement statement = conet.prepareStatement(sql);
                statement.setString(1, rfcEmpleado);
                ResultSet result = statement.executeQuery();

                if (result.next()) {
                    String correoEmpleado = result.getString("Correo");
                    double salarioEmpleado = result.getDouble("Salario");
                    String puestoEmpleado = result.getString("Puesto");

                    ModificacionEmpleado modificar = new ModificacionEmpleado(this, tablaEmpleados);
                    modificar.setDatos(rfcEmpleado, nombreEmpleado, apellidoPaternoEmpleado, apellidoMaternoEmpleado, correoEmpleado, salarioEmpleado, puestoEmpleado);
                    modificar.setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "No se encontraron datos del empleado en la base de datos.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al obtener los datos del empleado: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }


    }//GEN-LAST:event_btModificacionActionPerformed


    private void btBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBajaActionPerformed
        // Obtener la fila seleccionada en la tabla de empleados
        int filaSeleccionada = tablaEmpleados.getSelectedRow();

// Verificar si se ha seleccionado una fila válida
        if (filaSeleccionada != -1) {
            // Obtener el RFC del registro seleccionado
            String rfcEmpleadoAEliminar = (String) tablaEmpleados.getValueAt(filaSeleccionada, 0); // RFC es la primera columna

            // Construir un mensaje de confirmación con los datos del empleado seleccionado
            String mensajeConfirmacion = "¿Estás seguro de que deseas eliminar al empleado con RFC:\n" + rfcEmpleadoAEliminar + "?";

            // Mostrar un cuadro de diálogo de confirmación
            int confirmacion = JOptionPane.showConfirmDialog(null, mensajeConfirmacion, "Confirmar eliminación", JOptionPane.YES_NO_OPTION);

            // Si el usuario confirma la eliminación, proceder con la eliminación del registro
            if (confirmacion == JOptionPane.YES_OPTION) {
                // Construir la sentencia SQL para eliminar el registro que coincida con el RFC seleccionado
                String sql = "DELETE FROM Empleado WHERE RFC = ?";

                try {
                    // Crear una conexión a la base de datos
                    Connection conet = con1.getConnection();

                    // Crear una sentencia preparada con la consulta SQL
                    PreparedStatement statement = conet.prepareStatement(sql);

                    // Establecer el parámetro para el RFC del registro que deseas eliminar
                    statement.setString(1, rfcEmpleadoAEliminar);

                    // Ejecutar la sentencia SQL para eliminar el registro
                    int filasAfectadas = statement.executeUpdate();

                    // Verificar si se eliminó el registro exitosamente
                    if (filasAfectadas > 0) {
                        // Eliminar el registro seleccionado de la tabla
                        DefaultTableModel modelo = (DefaultTableModel) tablaEmpleados.getModel();
                        modelo.removeRow(filaSeleccionada);

                        // Mostrar un mensaje de éxito
                        JOptionPane.showMessageDialog(null, "Empleado eliminado correctamente.");
                        //this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(null, "No se pudo eliminar el registro.");
                    }
                } catch (SQLException e) {
                    // Manejar cualquier excepción que ocurra durante la ejecución de la consulta SQL
                    JOptionPane.showMessageDialog(null, "Error al eliminar el registro: " + e.getMessage());
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Por favor, seleccione un empleado para eliminar.");
        }

    }//GEN-LAST:event_btBajaActionPerformed

    private void tablaEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaEmpleadosMouseClicked

    }//GEN-LAST:event_tablaEmpleadosMouseClicked

    private void ntAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ntAltaActionPerformed
        // TODO add your handling code here:
        new AltaEmpleado().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ntAltaActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        // TODO add your handling code here:
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void AgregarCajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarCajeroActionPerformed
        int filaSeleccionada = tablaEmpleados.getSelectedRow();

        if (filaSeleccionada != -1) {
            String idEmpleado = tablaEmpleados.getValueAt(filaSeleccionada, 0).toString();  // Obtener el ID del empleado
            String correoEmpleado = tablaEmpleados.getValueAt(filaSeleccionada, 4).toString();  // Obtener el correo
            String puestoEmpleado = tablaEmpleados.getValueAt(filaSeleccionada, 6).toString();  // Obtener el puesto

            if (puestoEmpleado.equalsIgnoreCase("Cajero")) {
                Credenciales credenciales = new Credenciales(correoEmpleado, idEmpleado);
                credenciales.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "El usuario seleccionado no es un cajero.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Por favor, seleccione un empleado.");
        }

    }//GEN-LAST:event_AgregarCajeroActionPerformed

    private void inventario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventario1ActionPerformed
        // TODO add your handling code here:
        Inventario inventario = new Inventario();
        inventario.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_inventario1ActionPerformed

    private void CredencialesCajerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CredencialesCajerosActionPerformed
        // TODO add your handling code here:
        UsuariosCajeros cajero = new UsuariosCajeros();
        cajero.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CredencialesCajerosActionPerformed

    // Método para realizar la consulta a la base de datos y mostrar los resultados en un JTable
    public void consultar() {
        conet = con1.getConnection();
        String sql = "SELECT RFC, Nombre, Apellido_Paterno, Apellido_Materno, Correo, Salario, Puesto, FechaNacimiento FROM Empleado"; // Agregar FechaNacimiento a la consulta
        try {
            PreparedStatement statement = conet.prepareStatement(sql);
            ResultSet result = statement.executeQuery();

            // Se utiliza DefaultTableModel y fireTableDataChanged() para mejorar la velocidad de actualización
            modelo = (DefaultTableModel) tablaEmpleados.getModel();
            modelo.setRowCount(0);

            while (result.next()) {
                Object[] row = {
                    result.getString("RFC"),
                    result.getString("Nombre"),
                    result.getString("Apellido_Paterno"),
                    result.getString("Apellido_Materno"),
                    result.getString("Correo"),
                    result.getDouble("Salario"),
                    result.getString("Puesto"),
                    result.getDate("FechaNacimiento")
                };
                modelo.addRow(row);
            }

            // Notifica a la JTable que los datos han cambiado
            modelo.fireTableDataChanged();

        } catch (SQLException e) {
            //e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error al consultar la base de datos: " + e.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administradorr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administradorr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administradorr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administradorr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administradorr().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarCajero;
    private javax.swing.JButton CredencialesCajeros;
    private javax.swing.JButton btBaja;
    private javax.swing.JPanel btBuscar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btModificacion;
    private javax.swing.JButton inventario1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton ntAlta;
    private javax.swing.JTable tablaEmpleados;
    // End of variables declaration//GEN-END:variables
}
